### ISSUE TITLE
解包失败

### ISSUE THREAD

**Issue by YunfanMu** [XueDugu/ttpkgUnpacker#1]
解包后的原文件会出现在在rawPackages中。
Loading: out/111.pkg
8
12
Traceback (most recent call last):
  File "/Users/apple/Downloads/ttpkgUnpacker-main/ttpkgUnpacker/main.py", line 66, in <module>
    run_and_delete_ttpkg_js_files(js_folder)
  File "/Users/apple/Downloads/ttpkgUnpacker-main/ttpkgUnpacker/main.py", line 48, in run_and_delete_ttpkg_js_files
    Main(["", file_path]).run()
  File "/Users/apple/Downloads/ttpkgUnpacker-main/ttpkgUnpacker/controller/main/__init__.py", line 17, in run
    mpk = MPK.load(io)
  File "/Users/apple/Downloads/ttpkgUnpacker-main/ttpkgUnpacker/model/mpk.py", line 35, in load
    file_name = bytes(file_data).decode(encoding='ascii')  # 将文件名数据转换为字符串
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf3 in position 54: ordinal not in range(128)

**Comment by XueDugu** [comment]
你用的是release还是运行的代码？你运行时的输入的是文件夹的名称吗？不能输入包的名称哦！

**Comment by YunfanMu** [comment]
输入的是目录名，示例可以正常解，我这个不行

**Comment by XueDugu** [comment]
你用文本阅读器打开一下的包，如果开头是TPKG，应该能解，否则不一定行。

**Comment by XueDugu** [comment]
我主页的描述可能不够严谨，不好意思。

**Comment by YunfanMu** [comment]
TPKG51

**Comment by XueDugu** [comment]
额，实在不好意思，我只测试了我用过的小程序，这个我再去研究一下，如果改进了，再来通知您好吗？

**Comment by YunfanMu** [comment]
好，感谢。

**Comment by XueDugu** [comment]
我去看了一下代码，感觉没什么问题，需要解包的文件名字和路径名字不能出现汉字，有可能是因为出现汉字或者其他特殊字符导致识别文件名出了问题，您要不去确认一下。

**Comment by YunfanMu** [comment]
我看了一下，你这个只能解未加密的包，里面没有乱码，二进制文件跟微信小程序的结构差不多，我这个pkg是抖音小游戏的包，应该是经过加密后里面有乱码，结构也不同。



在 2023-08-03 13:01:17，"XueDugu" ***@***.***> 写道：

我去看了一下代码，感觉没什么问题，需要解包的文件名字和路径名字不能出现汉字，有可能是因为出现汉字或者其他特殊字符导致识别文件名出了问题，您要不去确认一下。

**Comment by XueDugu** [comment]
我试了几十个小程序都没问题，估计是小游戏单独做了加密的问题了，方便发一个小游戏的包给我吗？手边没有root的真机，模拟器不太好开小游戏，我用magisk改机了都开不了。如果可以的话，直接发我邮箱就行了，这样我方便针对小游戏的加密做优化，谢谢。22307130296@m.fudan.edu.cn

**Comment by XueDugu** [comment]
我用师兄的机子看了一下，其中有很多�，原本怀疑是特殊加载方法，但运行其他功能的时候再去把包拿下来发现�的位置不一样了，而且未加密的部分是连续的，因此可以基本排除使用了特殊加密方法，我估计抖音小程序也是标准的TPKG格式，但是，它很可能是动态加载的。如果有了完整的包，应该略加修改带代码还是可以解密的。

**Comment by XueDugu** [comment]
我只是提出一种猜想，也不一定对，也有可能是我没加载完抖音小游戏导致的，也有可能采用了一种和时间戳有关的动态加密技术。如果您有什么发现并且乐意分享给我的话，我也很愿意去学习。

**Comment by YunfanMu** [comment]
是的，按照抖音小程序官方文档的解释，为了优化加载时间，他们会动态调整ttpkg文件顺序，但是对于很多？字符是未知的，我无法判断这些字符是做什么的？是某个文件的一部分或是什么？我将官方文档流加载相关链接附在文末，希望对你有有所启发。https://developer.open-douyin.com/docs/resource/zh-CN/mini-app/develop/guide/basic-ability/data-load/what-is-data-loading

**Comment by YunfanMu** [comment]
另外值得一提的是，我发现除去开头的65字节标志位和信息位后，从66-73字节代表了某种信息，但在我尝试了几种方法后未分析出代表了什么。

**Comment by xiaowangio** [comment]
内存可以dump出来
